# Configuração de headers para fontes, CSS e JS
[[headers]]
for = "/assets/fonts/*.ttf"
[headers.values]
  Content-Type = "font/ttf"
  Access-Control-Allow-Origin = "*"
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/assets/fonts/*.woff"
[headers.values]
  Content-Type = "font/woff"
  Access-Control-Allow-Origin = "*"
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/assets/fonts/*.woff2"
[headers.values]
  Content-Type = "font/woff2"
  Access-Control-Allow-Origin = "*"
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.css"
[headers.values]
  Content-Type = "text/css"
  Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.js"
[headers.values]
  Content-Type = "application/javascript"
  Cache-Control = "public, max-age=31536000"
